Repository Starchasers/up, pull requests merged in 2020-10, with the labels that each got.

#161 make username editable by admin
  spring-app/src/main/kotlin/pl/starchasers/up/controller/admin/UserAdminController.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/dto/users/UpdateUserDTO.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/model/User.kt
  spring-app/src/main/kotlin/pl/starchasers/up/service/UserService.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/admin/UserAdminControllerTest.kt
Labels: enhancement

#106 fix plaintext files encoding
  gatsby-app/src/components/useFileUpload.js
  spring-app/build.gradle.kts
  spring-app/src/main/kotlin/pl/starchasers/up/service/CharsetDetectionService.kt
  spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/UploadControllerTest.kt
Labels: bug, enhancement

#174 Feature/configuration refactor
  spring-app/src/docs/asciidoc/index.adoc
  spring-app/src/main/kotlin/pl/starchasers/up/controller/admin/ConfigurationAdminController.kt
  spring-app/src/main/kotlin/pl/starchasers/up/controller/admin/UserAdminController.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/dto/users/UpdateUserDTO.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/dto/users/UserDTO.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/model/User.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/value/Email.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/value/FileSize.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/value/Milliseconds.kt
  spring-app/src/main/kotlin/pl/starchasers/up/data/value/Username.kt
  spring-app/src/main/kotlin/pl/starchasers/up/service/UserService.kt
  spring-app/src/main/kotlin/pl/starchasers/up/util/Util.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/UploadControllerTest.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/admin/ConfigurationAdminControllerTest.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/admin/UserAdminControllerTest.kt
Labels: backend only, enhancement
