Repository Starchasers/up, pull requests merged in 2020-06, with the labels that each got.

#70 fix method security annotations
  spring-app/src/main/kotlin/pl/starchasers/up/service/FileService.kt
  spring-app/src/test/kotlin/pl/starchasers/up/controller/AnonymousUploadControllerTest.kt
Labels: enhancement

#81 Fix multiple files select
  gatsby-app/src/components/boxes/MainPageBox.js
Labels: enhancement

#86 Feature/sharex config
  spring-app/src/main/kotlin/pl/starchasers/up/controller/UtilController.kt
  spring-app/src/main/resources/application.properties
  spring-app/src/test/resources/application.properties
Labels: enhancement

#90 Meta tags
  gatsby-app/gatsby-config.js
  gatsby-app/package-lock.json
  gatsby-app/package.json
  gatsby-app/src/components/blocks/MainBox/Box.js
  gatsby-app/src/components/blocks/MainBox/Shadow.js
  gatsby-app/src/components/elements/metaTags.js
  gatsby-app/src/components/globalStyles.js
  gatsby-app/src/components/layout.js
  gatsby-app/src/components/theme.js
  gatsby-app/src/pages/index.js
  gatsby-app/static/robots.txt
Labels: enhancement

#103 Update manifest names
  gatsby-app/gatsby-config.js
Labels: enhancement

#104 cors configuration
  spring-app/src/main/kotlin/pl/starchasers/up/configuration/WebSecurityConfiguration.kt
  spring-app/src/main/resources/application.properties
  spring-app/src/test/resources/application.properties
Labels: enhancement

#105 fix copy
  gatsby-app/src/components/boxes/AfterPageBox.js
Labels: bug, enhancement

#112 fix empty filename
  spring-app/src/main/kotlin/pl/starchasers/up/controller/AnonymousUploadController.kt
Labels: enhancement

#114 Changed icon to 256x256
  gatsby-app/src/components/elements/metaTags.js
Labels: enhancement

#115 Fix bottom
  gatsby-app/src/components/blocks/AfterUploadBox/DeleteTimeArea.js
Labels: bug
